<a href="https://colab.research.google.com/github/amrit100612/Internship-program_26/blob/main/Day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([[1,2],[7,8]])
b=  np.array([[4,5],[9,1]])
c= np.matrix([[1,2],[3,4]])
d= np.matrix([[5,6],[8,9]])
print("\nC", type(c))
print(c)
print("\nD", type(d))
print(d)
print("\n Operation on two ndarray obj. (Elementwise)")
print(a*b)
print("\n Operation on two matrix obj. (same as np.dot())")
print(c*d)


C <class 'numpy.matrix'>
[[1 2]
 [3 4]]

D <class 'numpy.matrix'>
[[5 6]
 [8 9]]

 Operation on two ndarray obj. (Elementwise)
[[ 4 10]
 [63  8]]

 Operation on two matrix obj. (same as np.dot())
[[21 24]
 [47 54]]


In [ ]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
print("a= ")
print(a)

print("\n With np Transpose function = ")
print(np.transpose(a))

print("\n With Ordinary Transpose method = ")
print(a.transpose())

print("\n With ndarray.1 Short form = ")
print(a.T)

a= 
[[1 2]
 [3 4]
 [5 6]]

 With np Transpose function = 
[[1 3 5]
 [2 4 6]]

 With Ordinary Transpose method = 
[[1 3 5]
 [2 4 6]]

 With ndarray.1 Short form = 
[[1 3 5]
 [2 4 6]]


In [ ]:
#trace
a=np.array([[2,2,1],[1,3,1],[1,2,2]])

print("\nDiagonal elements are:")
sum=0
#By_Loop
for i in range(len(a)):
      print(a[i][i])
      sum+=a[i][i]

print(f"\ntrace of a matrix:\n{sum}")

#By_Function
trace = np.trace(c)
print("Trace:",trace)


Diagonal elements are:
2
3
2

trace of a matrix:
7
Trace: 7


In [ ]:
#rank
import numpy as np
a = np.arange(1,10)
a.shape = (3,3)
print("a = ")
print(a)
print("rank of a : ")
print(np.linalg.matrix_rank(a))

a = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
rank of a : 
2


In [ ]:
#Determinant

import numpy as np
a=np.array([[2,2,1],[1,3,1],[1,2,2]])
det=np.linalg.det(a)
print(f"Determinant of a matrix:\n{det}")




Determinant of a matrix:
4.999999999999999


In [ ]:
#Inverse
import numpy as np
a=np.array([[2,2,1],[1,3,1],[1,2,2]])
inv=np.linalg.inv(a)
print(f"Inverse of a matrix:\n{inv}")


Inverse of a matrix:
[[ 0.8 -0.4 -0.2]
 [-0.2  0.6 -0.2]
 [-0.2 -0.4  0.8]]


In [ ]:
#Det=0 Error
import numpy as np
a=np.array([[2,8],[1,4]])
inv=np.linalg.inv(a)
print(f"Inverse of a matrix:\n{inv}")

LinAlgError: Singular matrix

In [ ]:
#psudo Inverse
import numpy as np
a=np.array([[2,8],[1,4]])
pinv=np.linalg.pinv(a)
print(f"Inverse of a matrix:\n{pinv}")

Inverse of a matrix:
[[0.02352941 0.01176471]
 [0.09411765 0.04705882]]


In [ ]:
#flattening
import numpy as np
a = np.arange(1,10)
a.shape = (3,3)
print("a = ")
print(a)
print("\nAfter flattening: ")
print(a.flatten())
print("\nAfter reshaping:")
print(a.reshape(-1))

a = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

After flattening: 
[1 2 3 4 5 6 7 8 9]

After reshaping:
[1 2 3 4 5 6 7 8 9]


In [ ]:
#Eigen value
import numpy as np
a=np.array([[2,2,1],[1,3,1],[1,2,2]])
w,v = np.linalg.eig(a)
print("Eigen Value")
print(w)
print("Eigen Vector")
print(v)

Eigen Value
[5. 1. 1.]
Eigen Vector
[[-0.57735027 -0.90453403  0.82529864]
 [-0.57735027  0.30151134 -0.52125218]
 [-0.57735027  0.30151134  0.21720572]]


In [ ]:
import pandas as pd
data=pd.read_csv('/content/sample_data/Years/1995.csv')
data.info()
print(data.shape)
data.head(20)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Years    20 non-null     int64 
 1   Product  20 non-null     object
 2   Price    20 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 612.0+ bytes
(20, 3)


Years    Product  Price
0    1995  Fast Food    200
1    1995      Sweet    150
2    1995  Fast Food    100
3    1995  Fast Food    250
4    1995  Fast Food    260
5    1995      Sweet    230
6    1995      Sweet    210
7    1995  Fast Food    120
8    1995      Sweet    150
9    1995  Fast Food    160
10   1995  Fast Food    140
11   1995      Sweet    180
12   1995  Fast Food    190
13   1995      Sweet    130
14   1995  Fast Food    123
15   1995      Sweet    210
16   1995      Sweet    250
17   1995  Fast Food    120
18   1995      Sweet    159
19   1995  Fast Food    160

from matplotlib import pyplot as plt
_df_12['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_13['Price'].plot(kind='hist', bins=20, title='Price')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_14.groupby('Product').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_15.plot(kind='scatter', x='index', y='Price', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['Price']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_16.sort_values('index', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Product')):
  _plot_series(series, series_name, i)
  fig.legend(title='Product', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('Price')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_17.sort_values('index', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Product')):
  _plot_series(series, series_name, i)
  fig.legend(title='Product', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Years']
  ys = series['Price']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_18.sort_values('Years', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Product')):
  _plot_series(series, series_name, i)
  fig.legend(title='Product', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Years')
_ = plt.ylabel('Price')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Years']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Years'}, axis=1)
              .sort_values('Years', ascending=True))
  xs = counted['Years']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_19.sort_values('Years', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Product')):
  _plot_series(series, series_name, i)
  fig.legend(title='Product', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Years')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_20['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_21['Price'].plot(kind='line', figsize=(8, 4), title='Price')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_22['Product'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_22, x='index', y='Product', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_23['Product'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_23, x='Price', y='Product', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
import pandas as pd
data=pd.read_csv('/content/sample_data/Years/1995.csv', delimiter = ',')
print(data)


    Years    Product  Price
0    1995  Fast Food    200
1    1995      Sweet    150
2    1995  Fast Food    100
3    1995  Fast Food    250
4    1995  Fast Food    260
5    1995      Sweet    230
6    1995      Sweet    210
7    1995  Fast Food    120
8    1995      Sweet    150
9    1995  Fast Food    160
10   1995  Fast Food    140
11   1995      Sweet    180
12   1995  Fast Food    190
13   1995      Sweet    130
14   1995  Fast Food    123
15   1995      Sweet    210
16   1995      Sweet    250
17   1995  Fast Food    120
18   1995      Sweet    159
19   1995  Fast Food    160


In [ ]:
#skipping same row of the csv file



data=pd.read_csv('/content/sample_data/read_data_with_skipping_row.csv',skiprows = 4)
data.info()
print(data)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Years    20 non-null     int64 
 1   Product  20 non-null     object
 2   Price    20 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 612.0+ bytes
    Years    Product  Price
0    1995  Fast Food    200
1    1995      Sweet    150
2    1995  Fast Food    100
3    1995  Fast Food    250
4    1995  Fast Food    260
5    1995      Sweet    230
6    1995      Sweet    210
7    1995  Fast Food    120
8    1995      Sweet    150
9    1995  Fast Food    160
10   1995  Fast Food    140
11   1995      Sweet    180
12   1995  Fast Food    190
13   1995      Sweet    130
14   1995  Fast Food    123
15   1995      Sweet    210
16   1995      Sweet    250
17   1995  Fast Food    120
18   1995      Sweet    159
19   1995  Fast Food    160


In [ ]:
import glob
file_list= glob.glob